use std::{os::unix::process::CommandExt, path::Path};

use anyhow::{Context, Result, bail};

use super::{SleepProfile, load, plugged};

/// Preserve the declarative lock/DPMS configuration; replace only unambiguous
/// sleep listeners. Refuse includes and custom sleep scripts instead of silently
/// running two independent sleep policies.
pub(super) fn render(
    base: &str,
    profile: &SleepProfile,
    executable: &Path,
    generation: &str,
) -> Result<String> {
    if generation.is_empty()
        || !generation
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
    {
        bail!("invalid idle countdown generation");
    }
    let mut result = format!(
        "# shelllist-idle-generation={generation}\n# shelllist-idle-minutes={}\n# Generated by bar-daemon; edit sleep profiles in Shelllist.\n",
        profile.sleep_minutes
    );
    let mut lines = base.lines();
    while let Some(line) = lines.next() {
        let code = config_code(line)?;
        if code.starts_with("listener") {
            anyhow::ensure!(
                code == "listener {",
                "managed hypridle requires listener blocks on separate lines"
            );
            let block = listener_block(line, &mut lines)?;
            if !is_sleep_listener(&block)? {
                result.extend(block.into_iter().flat_map(|line| [line, "\n"]));
            }
            continue;
        }
        anyhow::ensure!(
            !mentions_sleep(code),
            "custom sleep command outside a listener; remove it before enabling managed sleep"
        );
        result.extend([line, "\n"]);
    }
    // The native control owns one separate sleep listener. Base lock/DPMS
    // listeners and process-owned inhibitor cookies are never restarted.
    quoted_executable(executable)?;
    Ok(result)
}

fn quoted_executable(executable: &Path) -> Result<String> {
    let executable = executable
        .to_str()
        .context("bar-daemon executable path is not UTF-8")?;
    if executable.contains(['\n', '\r', '#', '{', '}']) {
        bail!("unsupported executable path in hypridle config");
    }
    Ok(format!("'{}'", executable.replace('\'', "'\\''")))
}

fn config_code(line: &str) -> Result<&str> {
    let code = line.split('#').next().unwrap_or("").trim();
    anyhow::ensure!(
        !(code.starts_with("source") && code.contains('=')),
        "managed hypridle does not support source includes; put lock/DPMS listeners in the base config"
    );
    Ok(code)
}

fn listener_block<'a>(
    first: &'a str,
    lines: &mut impl Iterator<Item = &'a str>,
) -> Result<Vec<&'a str>> {
    let mut block = vec![first];
    for line in lines {
        let code = config_code(line)?;
        block.push(line);
        if code == "}" {
            return Ok(block);
        }
        anyhow::ensure!(
            !code.starts_with("listener") && !code.contains(['{', '}']),
            "nested or inline hypridle listeners are not supported"
        );
    }
    bail!("unterminated hypridle listener")
}

fn mentions_sleep(command: &str) -> bool {
    command.contains("suspend")
        || command.contains("hibernate")
        || command.contains("powerSleep.")
        || command.contains("idle-sleep")
}

fn is_sleep_listener(lines: &[&str]) -> Result<bool> {
    let settings: Vec<_> = lines[1..lines.len() - 1]
        .iter()
        .map(|line| line.split('#').next().unwrap_or("").trim())
        .filter(|line| !line.is_empty())
        .collect();
    if !settings.iter().any(|line| mentions_sleep(line)) {
        return Ok(false);
    }
    let mut timeout = false;
    let mut action = false;
    for line in settings {
        let Some((key, value)) = line.split_once('=') else {
            bail!("invalid sleep listener");
        };
        match key.trim() {
            "timeout" if !timeout && value.trim().parse::<u32>().is_ok() => timeout = true,
            "on-timeout" if !action && canonical_sleep_command(value.trim()) => action = true,
            _ => bail!(
                "custom hypridle sleep listener cannot be safely replaced; keep only lock/DPMS listeners in the base config"
            ),
        }
    }
    if !timeout || !action {
        bail!("incomplete hypridle sleep listener");
    }
    Ok(true)
}

fn canonical_sleep_command(command: &str) -> bool {
    let parts: Vec<_> = command.split_whitespace().collect();
    parts.len() == 2
        && matches!(
            Path::new(parts[0])
                .file_name()
                .and_then(|name| name.to_str()),
            Some("systemctl" | "loginctl")
        )
        && matches!(parts[1], "suspend" | "hibernate" | "suspend-then-hibernate")
}

fn runtime_config() -> Result<std::path::PathBuf> {
    let runtime = std::env::var_os("XDG_RUNTIME_DIR").context("XDG_RUNTIME_DIR is required")?;
    Ok(Path::new(&runtime).join("bar-daemon/hypridle.conf"))
}

async fn control(connection: &zbus::Connection) -> Result<zbus::Proxy<'_>> {
    Ok(zbus::Proxy::new(
        connection,
        "org.laufan.Hypridle",
        "/org/laufan/Hypridle",
        "org.laufan.Hypridle1",
    )
    .await?)
}

pub(super) async fn live_state() -> Result<(u32, String, u32, u64, bool)> {
    let connection = super::user_systemd().await?;
    live_state_on(&connection).await
}

async fn live_state_on(connection: &zbus::Connection) -> Result<(u32, String, u32, u64, bool)> {
    let (state,): ((u32, String, u32, u64, bool),) = control(connection)
        .await?
        .call("GetState", &())
        .await
        .context("activate the updated native Hypridle control integration")?;
    Ok(state)
}

pub(super) async fn active_minutes() -> Result<u32> {
    Ok(live_state().await?.2)
}
pub(super) async fn active_generation() -> Result<String> {
    Ok(live_state().await?.1)
}

pub(super) async fn set_timeout(minutes: u32) -> Result<()> {
    let connection = super::user_systemd().await?;
    set_timeout_on(&connection, minutes).await
}

async fn set_timeout_on(connection: &zbus::Connection, minutes: u32) -> Result<()> {
    let (pid, generation, previous, _, _) = live_state_on(connection).await?;
    if previous == minutes {
        return Ok(());
    }
    let _: () = control(connection)
        .await?
        .call("SetTimeout", &(generation, minutes))
        .await
        .context("update only the managed sleep listener")?;
    let (current_pid, _, applied, _, _) = live_state_on(connection).await?;
    anyhow::ensure!(
        pid == current_pid && applied == minutes,
        "idle process changed or timeout update was not confirmed"
    );
    Ok(())
}

pub(super) async fn verify_episode(generation: &str, episode: u64) -> Result<()> {
    let (_, current, _, current_episode, idle) = live_state().await?;
    validate_episode(generation, episode, &current, current_episode, idle)
}

pub(super) fn validate_episode(
    generation: &str,
    episode: u64,
    current: &str,
    current_episode: u64,
    idle: bool,
) -> Result<()> {
    anyhow::ensure!(
        generation == current && episode == current_episode && idle,
        "idle episode ended, was inhibited, or its process/countdown changed; sleep cancelled"
    );
    Ok(())
}

pub(crate) async fn run(config: &Path, executable: &Path) -> Result<()> {
    let base = tokio::fs::read_to_string(config)
        .await
        .context("read base hypridle config")?;
    let generation = format!(
        "{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_nanos()
    );
    let daemon = std::env::current_exe()?;
    let selected: Result<String> = async {
        let policy = load().await?;
        render(
            &base,
            policy.profile(
                tokio::time::timeout(std::time::Duration::from_secs(2), plugged())
                    .await
                    .context("AC state lookup timed out")??,
            ),
            &daemon,
            &generation,
        )
    }
    .await;
    let path = runtime_config()?;
    let rendered = match selected {
        Ok(rendered) => Some(rendered),
        Err(error) => {
            tracing::error!(%error, "managed sleep unavailable; retaining lock/DPMS behavior");
            // Never lose automatic locking just because UPower or the saved
            // sleep policy is unavailable. If the base cannot be migrated,
            // retain it unchanged rather than adding a competing timer.
            render(
                &base,
                &SleepProfile {
                    sleep_minutes: 0,
                    hibernate_minutes: 0,
                },
                &daemon,
                &generation,
            )
            .ok()
        }
    };
    let managed = rendered.is_some();
    let minutes = rendered
        .as_ref()
        .and_then(|text| text.lines().nth(1))
        .and_then(|line| line.strip_prefix("# shelllist-idle-minutes="))
        .unwrap_or("0")
        .to_string();
    let selected_path = if let Some(rendered) = rendered {
        crate::paths::save_bytes_durable(&path, rendered.as_bytes())?;
        path.as_path()
    } else {
        let _ = tokio::fs::remove_file(&path).await;
        config
    };
    let error = std::process::Command::new(executable)
        .arg("--config")
        .arg(selected_path)
        .env("BAR_DAEMON_IDLE_MANAGED", if managed { "1" } else { "0" })
        .env("BAR_DAEMON_IDLE_GENERATION", &generation)
        .env("BAR_DAEMON_IDLE_MINUTES", minutes)
        .env("BAR_DAEMON_IDLE_COMMAND", quoted_executable(&daemon)?)
        .exec();
    Err(error).context("start managed hypridle")
}

#[cfg(test)]
mod tests {
    use super::render;
    use crate::sleep_policy::SleepProfile;
    use std::path::Path;

    struct FakeControl(std::sync::Arc<std::sync::Mutex<(u32, u32)>>);
    #[zbus::interface(name = "org.laufan.Hypridle1")]
    impl FakeControl {
        fn get_state(&self) -> ((u32, String, u32, u64, bool),) {
            let state = self.0.lock().unwrap();
            ((42, format!("42-{}", state.1), state.0, 7, true),)
        }
        fn set_timeout(&self, expected: &str, minutes: u32) {
            let mut state = self.0.lock().unwrap();
            assert_eq!(expected, format!("42-{}", state.1));
            state.0 = minutes;
            state.1 += 1;
        }
    }

    #[tokio::test]
    async fn live_timeout_updates_preserve_process_and_skip_unchanged_timeout() {
        let state = std::sync::Arc::new(std::sync::Mutex::new((30, 0)));
        let (_server, client) = crate::test_support::dbus_peer(|builder| {
            builder.serve_at("/org/laufan/Hypridle", FakeControl(state.clone()))
        })
        .await
        .unwrap();
        super::set_timeout_on(&client, 30).await.unwrap();
        assert_eq!(*state.lock().unwrap(), (30, 0));
        super::set_timeout_on(&client, 45).await.unwrap();
        assert_eq!(*state.lock().unwrap(), (45, 1));
        super::set_timeout_on(&client, 0).await.unwrap();
        assert_eq!(*state.lock().unwrap(), (0, 2));
        let (pid, generation, _, episode, idle) = super::live_state_on(&client).await.unwrap();
        assert_eq!(pid, 42);
        assert!(super::validate_episode(&generation, episode, &generation, episode, idle).is_ok());
        for (current, token, active) in [
            (generation.as_str(), episode, false),
            (generation.as_str(), episode + 1, true),
            ("replacement", episode, true),
        ] {
            assert!(super::validate_episode(&generation, episode, current, token, active).is_err());
        }
    }

    #[test]
    fn replaces_only_sleep_and_preserves_lock_dpms_and_inhibitors() {
        let base = "general {\n  before_sleep_cmd = loginctl lock-session\n}\nlistener {\n timeout=300\n on-timeout=loginctl lock-session\n}\nlistener {\n timeout=420\n on-timeout=hyprctl dispatch dpms off\n on-resume=hyprctl dispatch dpms on\n}\nlistener {\n timeout=1800\n on-timeout=/run/current-system/sw/bin/systemctl suspend\n}\n";
        let profile = SleepProfile {
            sleep_minutes: 15,
            hibernate_minutes: 120,
        };
        let rendered = render(base, &profile, Path::new("/test/bar-daemon"), "test-1").unwrap();
        assert!(rendered.starts_with("# shelllist-idle-generation=test-1\n"));
        assert!(rendered.contains("# shelllist-idle-minutes=15"));
        assert!(
            render(
                base,
                &profile,
                Path::new("/test/bar-daemon"),
                "unsafe; command"
            )
            .is_err()
        );
        assert!(rendered.contains("before_sleep_cmd = loginctl lock-session"));
        assert!(rendered.contains("on-resume=hyprctl dispatch dpms on"));
        assert!(!rendered.contains("systemctl suspend"));
        assert!(
            !rendered.contains("idle-sleep"),
            "native listener must not have a second config timer"
        );
        assert!(!rendered.contains("ignore_inhibit"));
        let never = render(
            base,
            &SleepProfile {
                sleep_minutes: 0,
                hibernate_minutes: 120,
            },
            Path::new("/test/bar-daemon"),
            "test-2",
        )
        .unwrap();
        assert!(!never.contains("idle-sleep"));
        assert!(never.contains("timeout=300"));
        for base in [
            "source = more.conf",
            "listener { timeout=30 }",
            "listener {\nlistener {\n}\n}",
            "listener {\nsource = more.conf\n}",
            "listener {\non-timeout = { nested }\n}",
            "listener {\n timeout=30\n on-timeout=lock && systemctl suspend\n}",
            "listener {\n timeout=30\n on-timeout=systemctl suspend\n on-resume=echo resumed\n}",
            "listener {\n timeout=30\n",
        ] {
            assert!(
                render(base, &profile, Path::new("/test/bar-daemon"), "test-3").is_err(),
                "{base}"
            );
        }
    }
}
