use std::{os::unix::process::CommandExt, path::Path};

use anyhow::{Context, Result, bail};

use super::{SleepProfile, load, plugged};

/// Preserve the declarative lock/DPMS configuration; replace only unambiguous
/// sleep listeners. Refuse includes and custom sleep scripts instead of silently
/// running two independent sleep policies.
pub(super) fn render(
    base: &str,
    profile: &SleepProfile,
    executable: &Path,
    generation: &str,
) -> Result<String> {
    if generation.is_empty()
        || !generation
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || byte == b'-')
    {
        bail!("invalid idle countdown generation");
    }
    let mut result = format!(
        "# shelllist-idle-generation={generation}\n# shelllist-idle-minutes={}\n# Generated by bar-daemon; edit sleep profiles in Shelllist.\n",
        profile.sleep_minutes
    );
    let mut listener: Option<Vec<&str>> = None;
    for line in base.lines() {
        let code = line.split('#').next().unwrap_or("").trim();
        if code.starts_with("source") && code.contains('=') {
            bail!(
                "managed hypridle does not support source includes; put lock/DPMS listeners in the base config"
            );
        }
        if code.starts_with("listener") {
            if code != "listener {" || listener.is_some() {
                bail!("managed hypridle requires listener blocks on separate lines");
            }
            listener = Some(vec![line]);
            continue;
        }
        if let Some(lines) = listener.as_mut() {
            lines.push(line);
            if code == "}" {
                let lines = listener.take().expect("listener is open");
                if !is_sleep_listener(&lines)? {
                    result.push_str(&lines.join("\n"));
                    result.push('\n');
                }
            } else if code.contains(['{', '}']) {
                bail!("nested or inline hypridle listeners are not supported");
            }
        } else {
            if mentions_sleep(code) {
                bail!(
                    "custom sleep command outside a listener; remove it before enabling managed sleep"
                );
            }
            result.push_str(line);
            result.push('\n');
        }
    }
    if listener.is_some() {
        bail!("unterminated hypridle listener");
    }
    if profile.sleep_minutes > 0 {
        let executable = executable
            .to_str()
            .context("bar-daemon executable path is not UTF-8")?;
        if executable.contains(['\n', '\r', '#', '{', '}']) {
            bail!("unsupported executable path in hypridle config");
        }
        let quoted = format!("'{}'", executable.replace('\'', "'\\''"));
        result.push_str(&format!("\nlistener {{\n  timeout = {}\n  on-timeout = {quoted} idle-sleep --sleep-minutes {} --generation {generation}\n}}\n", profile.sleep_minutes * 60, profile.sleep_minutes));
    }
    Ok(result)
}

fn mentions_sleep(command: &str) -> bool {
    command.contains("suspend")
        || command.contains("hibernate")
        || command.contains("powerSleep.")
        || command.contains("idle-sleep")
}

fn is_sleep_listener(lines: &[&str]) -> Result<bool> {
    let settings: Vec<_> = lines[1..lines.len() - 1]
        .iter()
        .map(|line| line.split('#').next().unwrap_or("").trim())
        .filter(|line| !line.is_empty())
        .collect();
    if !settings.iter().any(|line| mentions_sleep(line)) {
        return Ok(false);
    }
    let mut timeout = false;
    let mut action = false;
    for line in settings {
        let Some((key, value)) = line.split_once('=') else {
            bail!("invalid sleep listener");
        };
        match key.trim() {
            "timeout" if !timeout && value.trim().parse::<u32>().is_ok() => timeout = true,
            "on-timeout" if !action && canonical_sleep_command(value.trim()) => action = true,
            _ => bail!(
                "custom hypridle sleep listener cannot be safely replaced; keep only lock/DPMS listeners in the base config"
            ),
        }
    }
    if !timeout || !action {
        bail!("incomplete hypridle sleep listener");
    }
    Ok(true)
}

fn canonical_sleep_command(command: &str) -> bool {
    let parts: Vec<_> = command.split_whitespace().collect();
    parts.len() == 2
        && matches!(
            Path::new(parts[0])
                .file_name()
                .and_then(|name| name.to_str()),
            Some("systemctl" | "loginctl")
        )
        && matches!(parts[1], "suspend" | "hibernate" | "suspend-then-hibernate")
}

fn runtime_config() -> Result<std::path::PathBuf> {
    let runtime = std::env::var_os("XDG_RUNTIME_DIR").context("XDG_RUNTIME_DIR is required")?;
    Ok(Path::new(&runtime).join("bar-daemon/hypridle.conf"))
}

pub(super) async fn active_minutes() -> Result<u32> {
    let config = tokio::fs::read_to_string(runtime_config()?)
        .await
        .context("read managed hypridle state")?;
    config
        .lines()
        .nth(1)
        .and_then(|line| line.strip_prefix("# shelllist-idle-minutes="))
        .context("hypridle has not loaded a managed sleep profile")?
        .parse()
        .context("invalid managed idle timeout")
}

pub(super) async fn active_generation() -> Result<String> {
    let config = tokio::fs::read_to_string(runtime_config()?)
        .await
        .context("read active idle countdown")?;
    config
        .lines()
        .next()
        .and_then(|line| line.strip_prefix("# shelllist-idle-generation="))
        .map(str::to_owned)
        .context("hypridle has not loaded a managed countdown")
}

pub(super) async fn verify_generation(generation: &str) -> Result<()> {
    if active_generation().await? != generation {
        bail!("idle countdown restarted; ignoring a stale sleep callback");
    }
    Ok(())
}

pub(crate) async fn run(config: &Path, executable: &Path) -> Result<()> {
    let base = tokio::fs::read_to_string(config)
        .await
        .context("read base hypridle config")?;
    let generation = format!(
        "{}-{}",
        std::process::id(),
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)?
            .as_nanos()
    );
    let daemon = std::env::current_exe()?;
    let selected: Result<String> = async {
        let policy = load().await?;
        render(
            &base,
            policy.profile(plugged().await?),
            &daemon,
            &generation,
        )
    }
    .await;
    let path = runtime_config()?;
    let rendered = match selected {
        Ok(rendered) => Some(rendered),
        Err(error) => {
            tracing::error!(%error, "managed sleep unavailable; retaining lock/DPMS behavior");
            // Never lose automatic locking just because UPower or the saved
            // sleep policy is unavailable. If the base cannot be migrated,
            // retain it unchanged rather than adding a competing timer.
            render(
                &base,
                &SleepProfile {
                    sleep_minutes: 0,
                    hibernate_minutes: 0,
                },
                &daemon,
                &generation,
            )
            .ok()
        }
    };
    let selected_path = if let Some(rendered) = rendered {
        crate::paths::save_bytes_durable(&path, rendered.as_bytes())?;
        path.as_path()
    } else {
        let _ = tokio::fs::remove_file(&path).await;
        config
    };
    let error = std::process::Command::new(executable)
        .arg("--config")
        .arg(selected_path)
        .exec();
    Err(error).context("start managed hypridle")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn replaces_only_sleep_and_preserves_lock_dpms_and_inhibitors() {
        let base = "general {\n  before_sleep_cmd = loginctl lock-session\n}\nlistener {\n timeout=300\n on-timeout=loginctl lock-session\n}\nlistener {\n timeout=420\n on-timeout=hyprctl dispatch dpms off\n on-resume=hyprctl dispatch dpms on\n}\nlistener {\n timeout=1800\n on-timeout=/run/current-system/sw/bin/systemctl suspend\n}\n";
        let profile = SleepProfile {
            sleep_minutes: 15,
            hibernate_minutes: 120,
        };
        let rendered = render(base, &profile, Path::new("/test/bar-daemon"), "test-1").unwrap();
        assert!(rendered.starts_with("# shelllist-idle-generation=test-1\n"));
        assert!(rendered.contains("--generation test-1"));
        assert!(
            render(
                base,
                &profile,
                Path::new("/test/bar-daemon"),
                "unsafe; command"
            )
            .is_err()
        );
        assert!(rendered.contains("before_sleep_cmd = loginctl lock-session"));
        assert!(rendered.contains("on-resume=hyprctl dispatch dpms on"));
        assert!(!rendered.contains("systemctl suspend"));
        assert!(rendered.contains("timeout = 900"));
        assert!(rendered.contains("idle-sleep --sleep-minutes 15"));
        assert!(!rendered.contains("ignore_inhibit"));
        let never = render(
            base,
            &SleepProfile {
                sleep_minutes: 0,
                hibernate_minutes: 120,
            },
            Path::new("/test/bar-daemon"),
            "test-2",
        )
        .unwrap();
        assert!(!never.contains("idle-sleep"));
        assert!(never.contains("timeout=300"));
    }

    #[test]
    fn refuses_ambiguous_competing_sleep_configuration() {
        for base in [
            "source = more.conf",
            "listener { timeout=30 }",
            "listener {\n timeout=30\n on-timeout=lock && systemctl suspend\n}",
            "listener {\n timeout=30\n on-timeout=systemctl suspend\n on-resume=echo resumed\n}",
            "listener {\n timeout=30\n",
        ] {
            assert!(
                render(
                    base,
                    &SleepProfile::default(),
                    Path::new("/test/bar-daemon"),
                    "test-3",
                )
                .is_err(),
                "{base}"
            );
        }
    }
}
